# Generated by Django 3.2.8 on 2021-10-20 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('nivel', models.IntegerField(max_length=2)),
                ('link', models.CharField(max_length=100)),
                ('idProfesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.profesor')),
            ],
        ),
    ]
