# Generated by Django 3.2.8 on 2021-10-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_leccion', models.CharField(max_length=50)),
                ('nivel', models.IntegerField()),
                ('link', models.TextField()),
                ('descripcion', models.TextField()),
                ('numero_clase', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_profesor', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=20)),
                ('contrasenia', models.CharField(max_length=20)),
            ],
        ),
    ]
