# Generated by Django 3.2.8 on 2021-10-21 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='idprofesor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestionBD.profesor'),
        ),
    ]
