# Generated by Django 3.2.8 on 2021-10-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0007_auto_20211021_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='apellido_profesor',
            field=models.CharField(max_length=50),
        ),
    ]
