# Generated by Django 3.2.8 on 2021-10-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0009_remove_leccion_numero_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leccion',
            name='link',
            field=models.CharField(max_length=600),
        ),
    ]
