# Generated by Django 3.2.8 on 2021-11-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0010_alter_leccion_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
                ('contraseña_estudiante', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='contrasenia',
            new_name='contraseña',
        ),
    ]
