# Generated by Django 3.2.8 on 2021-11-06 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0011_auto_20211105_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visto', models.IntegerField()),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionBD.estudiante')),
                ('id_leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionBD.leccion')),
            ],
        ),
    ]
