# Generated by Django 3.2.8 on 2021-11-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0013_alter_cursa_visto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursa',
            name='visto',
            field=models.BooleanField(),
        ),
    ]
