# Generated by Django 3.2.8 on 2021-11-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0014_alter_cursa_visto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='correo',
            new_name='correo_estudiante',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apellidoM_estudiante',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apellidoP_estudiante',
            field=models.CharField(default='b', max_length=50),
        ),
    ]
