# Generated by Django 3.2.8 on 2021-11-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0016_auto_20211106_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursa',
            name='id_estudiante',
        ),
        migrations.AddField(
            model_name='leccion',
            name='orden',
            field=models.IntegerField(null=True),
        ),
    ]
