# Generated by Django 3.2.8 on 2021-11-09 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0017_auto_20211109_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursa',
            name='id_profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionBD.profesor'),
        ),
    ]
