# Generated by Django 3.2.8 on 2021-11-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0020_cursa_id_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cancion', models.CharField(max_length=300)),
                ('grupo_artista', models.CharField(max_length=200)),
                ('imagen_cancion', models.ImageField(blank=True, default='', upload_to='static/Imagenes')),
            ],
        ),
    ]
