# Generated by Django 3.2.8 on 2021-11-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0022_auto_20211125_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='genero_musica',
            field=models.CharField(max_length=100),
        ),
    ]
