# Generated by Django 3.2.8 on 2021-11-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0023_alter_cancion_genero_musica'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='redireccion_cancion',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='grupo_artista',
            field=models.CharField(max_length=100),
        ),
    ]
