# Generated by Django 3.2.8 on 2021-11-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0025_alter_cancion_redireccion_cancion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='genero_musica',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='grupo_artista',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='nombre_cancion',
            field=models.TextField(),
        ),
    ]
