# Generated by Django 3.2.8 on 2021-12-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0026_auto_20211130_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='acordes_imagenes',
            field=models.CharField(default='d', max_length=250),
        ),
        migrations.AddField(
            model_name='cancion',
            name='acordes_letra',
            field=models.TextField(default='d'),
        ),
        migrations.AddField(
            model_name='cancion',
            name='acordes_nombres',
            field=models.CharField(default='d', max_length=200),
        ),
        migrations.AddField(
            model_name='cancion',
            name='fecha_album',
            field=models.CharField(default='f', max_length=60),
        ),
        migrations.AddField(
            model_name='cancion',
            name='link_video',
            field=models.CharField(default='f', max_length=60),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='genero_musica',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='grupo_artista',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='nombre_cancion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='redireccion_cancion',
            field=models.CharField(max_length=5),
        ),
    ]
