# Generated by Django 3.2.8 on 2021-12-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0027_auto_20211201_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='acordes_imagenes',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='acordes_letra',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='acordes_nombres',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='fecha_album',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='link_video',
            field=models.CharField(max_length=60),
        ),
    ]
