# Generated by Django 3.2.8 on 2021-12-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0028_auto_20211201_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='acordes_imagenes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='acordes_nombres',
            field=models.TextField(),
        ),
    ]
