# Generated by Django 3.2.8 on 2021-12-02 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0029_auto_20211201_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='redireccion_cancion',
        ),
    ]
