<<<<<<< HEAD
# Generated by Django 3.2.8 on 2021-12-02 20:40
=======
# Generated by Django 3.2.8 on 2021-12-02 21:05
>>>>>>> b6e404d704249915b02885ff85b2f78888721729

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBD', '0030_remove_cancion_redireccion_cancion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='acordes_nombres',
        ),
    ]
